AWSTemplateFormatVersion: '2010-09-09'
Description: Hyku solr stack
Parameters:
  StackName:
    Type: String
    Description: Name of the ElasticBeanstalk environment
  ApplicationName:
    Type: String
    Description: Name of the Solr environment
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the EB instances
  MinSize:
    Type: Number
    Description: Minimum number of instances
  MaxSize:
    Type: Number
    Description: Maximum number of instances
  InstanceType:
    Type: String
    Description: The EC2 instance type
  HealthReportingSystemType:
    Type: String
    Description: Health reporting system
  S3Bucket:
    Type: String
    Description: Bucket with Solr source bundle
  S3Key:
    Type: String
    Description: Key for Solr source bundle
  SubnetID:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of an existing subnet IDs to use for the load balancer and auto
      scaling group
  SecurityGroups:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: A list of security groups, such as sg-a123fd85
  LBSecurityGroups:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: A list of security groups, such as sg-a123fd85
  ZookeeperHostURL:
    Type: String
    Description: comma separated list of existing zk hosts
  HostedZoneName:
    Type: String
    Description: Route53 zone to create an alias in
Resources:
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [ec2.amazonaws.com]
          Action: ['sts:AssumeRole']
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkMulticontainerDocker
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles: [!Ref 'EC2Role']
  SolrApplicationVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName: !Ref 'ApplicationName'
      Description: Solr service version
      SourceBundle:
        S3Bucket: !Ref 'S3Bucket'
        S3Key: !Ref 'S3Key'
  SolrEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref 'ApplicationName'
      Description: Solr EB Environment
      EnvironmentName: !Sub ${StackName}-solr
      TemplateName: !Ref 'SolrConfigurationTemplate'
      VersionLabel: !Ref 'SolrApplicationVersion'
      OptionSettings:
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: ZK_HOST
          Value: !Ref 'ZookeeperHostURL'
  SolrConfigurationTemplate:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName: !Ref 'ApplicationName'
      Description: Solr configuration template
      OptionSettings:
        - Namespace: aws:autoscaling:asg
          OptionName: MinSize
          Value: !Ref 'MinSize'
        - Namespace: aws:autoscaling:asg
          OptionName: MaxSize
          Value: !Ref 'MaxSize'
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: InstanceType
          Value: !Ref 'InstanceType'
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: EC2KeyName
          Value: !Ref 'KeyName'
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: IamInstanceProfile
          Value: !Ref 'EC2InstanceProfile'
        - Namespace: aws:ec2:vpc
          OptionName: ELBScheme
          Value: internal
        - Namespace: aws:ec2:vpc
          OptionName: Subnets
          Value: !Join [',', !Ref 'SubnetID']
        - Namespace: aws:ec2:vpc
          OptionName: ELBSubnets
          Value: !Join [',', !Ref 'SubnetID']
        - Namespace: aws:elb:listener:80
          OptionName: ListenerProtocol
          Value: HTTP
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: SSHSourceRestriction
          Value: tcp, 22, 22, 10.0.0.0/16
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: SecurityGroups
          Value: !Join [',', !Ref 'SecurityGroups']
        - Namespace: aws:elb:loadbalancer
          OptionName: SecurityGroups
          Value: !Join [',', !Ref 'LBSecurityGroups']
        - Namespace: aws:elb:loadbalancer
          OptionName: CrossZone
          Value: 'true'
        - Namespace: aws:elb:policies
          OptionName: ConnectionDrainingEnabled
          Value: 'true'
        - Namespace: aws:autoscaling:trigger
          OptionName: MeasureName
          Value: CPUUtilization
        - Namespace: aws:autoscaling:trigger
          OptionName: Statistic
          Value: Maximum
        - Namespace: aws:autoscaling:trigger
          OptionName: Unit
          Value: Percent
        - Namespace: aws:autoscaling:trigger
          OptionName: LowerThreshold
          Value: '10'
        - Namespace: aws:autoscaling:trigger
          OptionName: UpperThreshold
          Value: '90'
        - Namespace: aws:autoscaling:updatepolicy:rollingupdate
          OptionName: RollingUpdateEnabled
          Value: 'true'
        - Namespace: aws:autoscaling:updatepolicy:rollingupdate
          OptionName: RollingUpdateType
          Value: Health
        - Namespace: aws:autoscaling:updatepolicy:rollingupdate
          OptionName: MaxBatchSize
          Value: '1'
        - Namespace: aws:autoscaling:updatepolicy:rollingupdate
          OptionName: MinInstancesInService
          Value: '2'
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: EnvironmentType
          Value: LoadBalanced
        - Namespace: aws:elasticbeanstalk:command
          OptionName: DeploymentPolicy
          Value: RollingWithAdditionalBatch
        - Namespace: aws:elasticbeanstalk:command
          OptionName: BatchSizeType
          Value: Fixed
        - Namespace: aws:elasticbeanstalk:command
          OptionName: BatchSize
          Value: '1'
        - Namespace: aws:elasticbeanstalk:healthreporting:system
          OptionName: SystemType
          Value: !Ref 'HealthReportingSystemType'
        - Namespace: aws:elasticbeanstalk:application
          OptionName: Application Healthcheck URL
          Value: HTTP:8983/solr/
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: ServiceRole
          Value: aws-elasticbeanstalk-service-role
        - Namespace: aws:elasticbeanstalk:managedactions
          OptionName: ManagedActionsEnabled
          Value: 'false'
        - Namespace: aws:elb:listener:80
          OptionName: ListenerProtocol
          Value: HTTP
        - Namespace: aws:elb:listener:80
          OptionName: InstancePort
          Value: '8983'
      SolutionStackName: 64bit Amazon Linux 2017.09 v2.9.2 running Multi-container Docker 17.12.0-ce (Generic)
  EBRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Sub 'solr.${HostedZoneName}'
      HostedZoneName: !Ref 'HostedZoneName'
      Type: CNAME
      TTL: '900'
      ResourceRecords:
      - !GetAtt [SolrEnvironment, EndpointURL]
Outputs:
  URL:
    Value: !Sub http://${EBRecordSet}/solr/
