AWSTemplateFormatVersion: '2010-09-09'
Description: Hyku application webapp tier
Parameters:
  StackName:
    Type: String
    Description: Name of the ElasticBeanstalk environment
  ApplicationName:
    Type: String
    Description: Name of the ElasticBeanstalk environment
  VersionLabel:
    Type: String
    Description: Name of the ElasticBeanstalk version
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the ECS instances
  MinSize:
    Type: Number
    Description: Minimum number of instances
  MaxSize:
    Type: Number
    Description: Maximum number of instances
  PublicSubnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of an existing subnet IDs to use for the load balancer
  PrivateSubnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of an existing subnet IDs to use for the auto scaling group
  SecurityGroups:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: A list of security groups, such as sg-a123fd85.
  LBSecurityGroups:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: A list of security groups, such as sg-a123fd85.
  HostedZoneName:
    Type: String
    Description: Route53 zone to create an alias in
  SecretKeyBase:
    Type: String
    Description: Secret key for Rails
    NoEcho: 'true'
  FcrepoUrl:
    Type: String
    Description: URL to Fedora
  SolrUrl:
    Type: String
    Description: URL to Solr
  ZookeeperHosts:
    Type: String
    Description: A list of zookeeper host IP + ports
  RedisHost:
    Type: String
    Description: URL to Redis
  RedisPort:
    Type: String
    Description: Redis Port
  RDSDatabaseName:
    Type: String
    Description: Database name
  RDSUsername:
    Type: String
    Description: Username for Database
  RDSPassword:
    Type: String
    Description: Password for Database
    NoEcho: 'true'
  RDSHostname:
    Type: String
    Description: Hostname for RDS Database
  RDSPort:
    Type: String
    Description: Database Port
  QueuePrefix:
    Type: String
    Description: SQS Queue prefix
  DefaultQueue:
    Type: String
    Description: SQS Default Queue
  IamInstanceProfile:
    Type: String
    Description: ARN for an IAM profile to assign to the EC2 instances
  UploadBucket:
    Type: String
    Description: S3 Bucket to store uploaded files into
  InstanceType:
    Type: String
    Description: The EC2 instance type
  HealthReportingSystemType:
    Type: String
    Description: Health reporting system
  BeanstalkSNSTopic:
    Type: String
    Description: SNS Topic for Beanstalk application to write change events to
  SSLCertificateId:
    Type: String
    Description: The Amazon Resource Name (ARN) of the SSL certificate
  GoogleAnalyticsId:
    Type: String
    Description: The Google Analytics id, e.g UA-111111-1
  EnableOpenSignup:
    Type: String
    Description: True to allow open self-signup, false to disable
  DisableOpenTenantCreation:
    Type: String
    Description: True to restrict tenant creation to admins, false to open creation to any registered users
  AccountInvitationFromEmail:
    Type: String
    Description: Email address from which account invitations are sent
  ContactEmail:
    Type: String
    Description: Email address to which contact form messages are sent
  GeonamesUsername:
    Type: String
    Description: The registered Geonames account name
  HoneybadgerApiKey:
    Type: String
    Description: The api key for honeybadger.io
  LogzioKey:
    Type: String
    Description: The logz.io key
Conditions:
  HasSSLCertificate: !Not [!Equals [!Ref 'SSLCertificateId', '']]
Mappings:
  AWSRegionToBeanstalkHostedZoneId:
    us-east-1:
      HostedZoneId: Z3DZXE0Q79N41H
    us-west-1:
      HostedZoneId: Z1M58G0W56PQJA
    us-west-2:
      HostedZoneId: Z33MTJ483KN6FU
    eu-west-1:
      HostedZoneId: Z3NF1Z3NOM5OY2
    eu-central-1:
      HostedZoneId: Z215JYRZR1TBD5
    ap-northeast-1:
      HostedZoneId: Z2YN17T5R711GT
    ap-southeast-1:
      HostedZoneId: Z1WI8VXHPB1R38
    ap-southeast-2:
      HostedZoneId: Z2999QAZ9SRTIC
    sa-east-1:
      HostedZoneId: Z2ES78Y61JGQKS
Resources:
  HyboxConfigurationTemplate:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName: !Ref 'ApplicationName'
      Description: Hybox configuration template
      OptionSettings:
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: InstanceType
          Value: !Ref 'InstanceType'
        - Namespace: aws:ec2:vpc
          OptionName: Subnets
          Value: !Join [',', !Ref 'PrivateSubnets']
        - Namespace: aws:ec2:vpc
          OptionName: ELBSubnets
          Value: !Join [',', !Ref 'PublicSubnets']
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: EC2KeyName
          Value: !Ref 'KeyName'
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: SSHSourceRestriction
          Value: tcp, 22, 22, 10.0.0.0/16
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: SecurityGroups
          Value: !Join [',', !Ref 'SecurityGroups']
        - Namespace: aws:elb:loadbalancer
          OptionName: SecurityGroups
          Value: !Join [',', !Ref 'LBSecurityGroups']
        - Namespace: aws:elb:loadbalancer
          OptionName: CrossZone
          Value: 'true'
        - Namespace: aws:elb:policies
          OptionName: ConnectionDrainingEnabled
          Value: 'true'
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: IamInstanceProfile
          Value: !Ref 'IamInstanceProfile'
        - Namespace: aws:autoscaling:asg
          OptionName: MinSize
          Value: !Ref 'MinSize'
        - Namespace: aws:autoscaling:asg
          OptionName: MaxSize
          Value: !Ref 'MaxSize'
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: EnvironmentType
          Value: LoadBalanced
        - Namespace: aws:elasticbeanstalk:command
          OptionName: DeploymentPolicy
          Value: Immutable
        - Namespace: aws:autoscaling:updatepolicy:rollingupdate
          OptionName: RollingUpdateEnabled
          Value: 'true'
        - Namespace: aws:autoscaling:updatepolicy:rollingupdate
          OptionName: RollingUpdateType
          Value: Health
        - Namespace: aws:elasticbeanstalk:application
          OptionName: Application Healthcheck URL
          Value: /is_it_working
        - Namespace: aws:elasticbeanstalk:healthreporting:system
          OptionName: SystemType
          Value: !Ref 'HealthReportingSystemType'
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: ServiceRole
          Value: aws-elasticbeanstalk-service-role
        - Namespace: aws:elasticbeanstalk:sns:topics
          OptionName: Notification Topic ARN
          Value: !Ref 'BeanstalkSNSTopic'
        - Namespace: aws:autoscaling:trigger
          OptionName: LowerThreshold
          Value: '30'
        - Namespace: aws:autoscaling:trigger
          OptionName: MeasureName
          Value: CPUUtilization
        - Namespace: aws:autoscaling:trigger
          OptionName: Statistic
          Value: Maximum
        - Namespace: aws:autoscaling:trigger
          OptionName: Unit
          Value: Percent
        - Namespace: aws:autoscaling:trigger
          OptionName: UpperThreshold
          Value: '85'
        - Namespace: aws:elb:listener:80
          OptionName: ListenerProtocol
          Value: HTTP
        - !If
          - HasSSLCertificate
          -
            Namespace: 'aws:elb:listener:443'
            OptionName: SSLCertificateId
            Value: !Ref 'SSLCertificateId'
          - !Ref 'AWS::NoValue'
        - !If
          - HasSSLCertificate
          -
            Namespace: 'aws:elb:listener:443'
            OptionName: InstancePort
            Value: '80'
          - !Ref 'AWS::NoValue'
        - !If
          - HasSSLCertificate
          -
            Namespace: 'aws:elb:listener:443'
            OptionName: ListenerProtocol
            Value: HTTPS
          - !Ref 'AWS::NoValue'
        - Namespace: aws:elasticbeanstalk:managedactions:platformupdate
          OptionName: UpdateLevel
          Value: minor
        - Namespace: aws:elasticbeanstalk:managedactions:platformupdate
          OptionName: InstanceRefreshEnabled
          Value: 'true'
        - Namespace: aws:elasticbeanstalk:managedactions
          OptionName: ManagedActionsEnabled
          Value: 'true'
        - Namespace: aws:elasticbeanstalk:managedactions
          OptionName: PreferredStartTime
          Value: Sun:00:00
      SolutionStackName: 64bit Amazon Linux 2017.09 v2.7.2 running Ruby 2.3 (Puma)
  WebappEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref 'ApplicationName'
      Description: Hybox Environment
      EnvironmentName: !Sub ${StackName}-webapp
      TemplateName: !Ref 'HyboxConfigurationTemplate'
      VersionLabel: !Ref 'VersionLabel'
      OptionSettings:
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: STACK_NAME
        Value: !Ref 'StackName'
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: SECRET_KEY_BASE
        Value: !Ref 'SecretKeyBase'
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: RAILS_GROUPS
        Value: aws
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: RAILS_SERVE_STATIC_FILES
        Value: 'true'
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: SOLR_URL
        Value: !Ref 'SolrUrl'
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: SETTINGS__SOLR__URL
        Value: !Ref 'SolrUrl'
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: FEDORA_URL
        Value: !Ref 'FcrepoUrl'
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: DISABLE_REDIS_CLUSTER
        Value: 'true'
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: REDIS_HOST
        Value: !Ref 'RedisHost'
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: REDIS_PORT
        Value: !Ref 'RedisPort'
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: SETTINGS__ZOOKEEPER__CONNECTION_STR
        Value: !Ref 'ZookeeperHosts'
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: SETTINGS__MULTITENANCY__DEFAULT_HOST
        Value: !Sub '%{tenant}.${StackName}.${HostedZoneName}'
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: SETTINGS__MULTITENANCY__ADMIN_HOST
        Value: !Sub ${StackName}.${HostedZoneName}
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: SETTINGS__MULTITENANCY__ADMIN_ONLY_TENANT_CREATION
        Value: !Ref 'DisableOpenTenantCreation'
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: RDS_DB_NAME
        Value: !Ref 'RDSDatabaseName'
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: RDS_USERNAME
        Value: !Ref 'RDSUsername'
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: RDS_PASSWORD
        Value: !Ref 'RDSPassword'
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: RDS_HOSTNAME
        Value: !Ref 'RDSHostname'
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: RDS_PORT
        Value: !Ref 'RDSPort'
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: SETTINGS__ACTIVE_JOB__QUEUE_ADAPTER
        Value: better_active_elastic_job
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: SETTINGS__ACTIVE_JOB_QUEUE__URL
        Value: !Ref 'DefaultQueue'
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: DISABLE_SQS_CONSUMER
        Value: 'true'
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: AWS_REGION
        Value: !Ref 'AWS::Region'
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: SETTINGS__S3__UPLOAD_BUCKET
        Value: !Ref 'UploadBucket'
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: SETTINGS__GOOGLE_ANALYTICS_ID
        Value: !Ref 'GoogleAnalyticsId'
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: SETTINGS__DEVISE__ACCOUNT_SIGNUP
        Value: !Ref 'EnableOpenSignup'
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: SETTINGS__DEVISE__INVITATION_FROM_EMAIL
        Value: !Ref 'AccountInvitationFromEmail'
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: SETTINGS__CONTACT_EMAIL
        Value: !Ref 'ContactEmail'
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: SETTINGS__GEONAMES_USERNAME
        Value: !Ref 'GeonamesUsername'
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: HONEYBADGER_ENV
        Value: !Ref 'StackName'
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: HONEYBADGER_API_KEY
        Value: !Ref 'HoneybadgerApiKey'
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: LOGZIO_KEY
        Value: !Ref 'LogzioKey'
      - !If
        - HasSSLCertificate
        -
          Namespace: 'aws:elasticbeanstalk:application:environment'
          OptionName: SETTINGS__SSL_CONFIGURED
          Value: 'true'
        - !Ref 'AWS::NoValue'
  EBRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Sub ${StackName}.${HostedZoneName}
      HostedZoneName: !Ref 'HostedZoneName'
      Type: A
      AliasTarget:
        DNSName: !GetAtt [WebappEnvironment, EndpointURL]
        HostedZoneId: !FindInMap [AWSRegionToBeanstalkHostedZoneId, !Ref 'AWS::Region',
          HostedZoneId]
  EBWildcardRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Sub '*.${StackName}.${HostedZoneName}'
      HostedZoneName: !Ref 'HostedZoneName'
      Type: A
      AliasTarget:
        DNSName: !GetAtt [WebappEnvironment, EndpointURL]
        HostedZoneId: !FindInMap [AWSRegionToBeanstalkHostedZoneId, !Ref 'AWS::Region',
          HostedZoneId]
Outputs:
  EnvironmentName:
    Value: !Ref 'WebappEnvironment'
  URL:
    Description: URL of the AWS Elastic Beanstalk Environment
    Value: !Sub http://${EBRecordSet}
